=== QHCrypto/bonc/bonc_frontend_output.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "version": {
      "const": 0
    },
    "info": {
      "type": "object",
      "title": "加密算法信息",
      "properties": {
        "categories": {
          "type": "array",
          "title": "加密算法类别",
          "items": {
            "enum": [
              "block_cipher",
              "hash_function",
              "stream_cipher",
              "aead",
              "ae",
              "mac"
            ]
          }
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "meta_parameters": {
      "type": "array",
      "title": "元参数（超参数）",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "value": {
            "oneOf": [
              {
                "type": "integer"
              },
              {
                "type": "string"
              }
            ]
          }
        }
      }
    },
    "components": {
      "type": "object",
      "title": "解析得到的加密算法组件",
      "properties": {
        "sboxes": {
          "type": "array",
          "title": "所有 S-盒定义",
          "items": {
            "type": "object",
            "title": "单个 S-盒",
            "properties": {
              "name": {
                "type": "string"
              },
              "value": {
                "type": "array",
                "items": {
                  "type": "integer"
                }
              },
              "input_width": {
                "type": "integer"
              },
              "output_width": {
                "type": "integer"
              }
            }
          },
          "required": [
            "name",
            "value"
          ]
        }
      }
    },
    "inputs": {
      "type": "array",
      "title": "所有传入算法的输入符号",
      "items": {
        "type": "object",
        "title": "单块算法输入",
        "properties": {
          "name": {
            "type": "string"
          },
          "size": {
            "type": "integer"
          }
        },
        "required": [
          "name",
          "size"
        ]
      }
    },
    "outputs": {
      "type": "array",
      "title": "所有作为算法输出的符号",
      "items": {
        "type": "object",
        "title": "单块算法输出",
        "properties": {
          "name": {
            "type": "string"
          },
          "size": {
            "type": "integer"
          },
          "expressions": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/bit_expression"
            }
          }
        },
        "required": [
          "name",
          "expressions"
        ]
      }
    },
    "iterations": {
      "type": "array",
      "title": "轮次迭代信息",
      "items": {
        "type": "object",
        "title": "内存块状态更新情况",
        "properties": {
          "name": {
            "type": "string"
          },
          "size": {
            "type": "integer"
          },
          "update_expressions": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/bit_expression"
            }
          }
        },
        "required": [
          "name",
          "size",
          "update_expressions"
        ]
      }
    }
  },
  "required": [
    "version",
    "info",
    "inputs",
    "outputs",
    "iterations"
  ],
  "definitions": {
    "bit_expression": {
      "oneOf": [
        {
          "$ref": "#/definitions/read_expression"
        },
        {
          "$ref": "#/definitions/lookup_expression"
        },
        {
          "$ref": "#/definitions/constant_expression"
        },
        {
          "$ref": "#/definitions/unary_expression"
        },
        {
          "$ref": "#/definitions/binary_expression"
        }
      ]
    },
    "read_expression": {
      "type": "object",
      "title": "内存读取",
      "properties": {
        "type": {
          "const": "read"
        },
        "target_kind": {
          "enum": [
            "input",
            "state"
          ]
        },
        "target_name": {
          "type": "string"
        },
        "offset": {
          "type": "integer"
        }
      },
      "required": [
        "type",
        "target_kind",
        "target_name",
        "offset"
      ]
    },
    "lookup_expression": {
      "type": "object",
      "title": "查表",
      "properties": {
        "type": {
          "const": "lookup"
        },
        "table_name": {
          "type": "string"
        },
        "inputs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/bit_expression"
          }
        },
        "output_offset": {
          "type": "integer"
        }
      },
      "required": [
        "type",
        "table_name",
        "inputs",
        "output_offset"
      ]
    },
    "constant_expression": {
      "type": "object",
      "title": "常量",
      "properties": {
        "type": {
          "const": "constant"
        },
        "value": {
          "enum": [
            0,
            1
          ]
        }
      },
      "required": [
        "type",
        "value"
      ]
    },
    "unary_expression": {
      "type": "object",
      "title": "一元表达式",
      "properties": {
        "type": {
          "const": "unary"
        },
        "operator": {
          "enum": [
            "not"
          ]
        },
        "operand": {
          "$ref": "#/definitions/bit_expression"
        }
      },
      "required": [
        "type",
        "operator",
        "operand"
      ]
    },
    "binary_expression": {
      "type": "object",
      "title": "二元表达式",
      "properties": {
        "type": {
          "const": "binary"
        },
        "operator": {
          "enum": [
            "and",
            "or",
            "xor"
          ]
        },
        "left": {
          "$ref": "#/definitions/bit_expression"
        },
        "right": {
          "$ref": "#/definitions/bit_expression"
        }
      },
      "required": [
        "type",
        "operator",
        "left",
        "right"
      ]
    }
  }
}

=== QHCrypto/bonc/bonc_round1.json
{"components":{"sboxes":[{"input_width":4,"name":"const_arr1","output_width":4,"value":[1,10,4,12,6,15,3,9,2,13,11,7,5,0,8,14]}]},"info":{},"inputs":[{"name":"key","size":32},{"name":"plaintext","size":16}],"iterations":[{"name":"0/0","size":32,"update_expressions":[{"offset":64,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":65,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":66,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":67,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":68,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":69,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":70,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":71,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":72,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":73,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":74,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":75,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":76,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":77,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":78,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":79,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":80,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":81,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":82,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":83,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":84,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":85,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":86,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":87,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":88,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":89,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":90,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":91,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":92,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":93,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":94,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":95,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":96,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":97,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":98,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":99,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":100,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":101,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":102,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":103,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":104,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":105,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":106,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":107,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":108,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":109,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":110,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":111,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":112,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":113,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":114,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":115,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":116,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":117,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":118,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":119,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":120,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":121,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":122,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":123,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":124,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":125,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":126,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":127,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":128,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":129,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":130,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":131,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":132,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":133,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":134,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":135,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":136,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":137,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":138,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":139,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":140,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":141,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":142,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":143,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":144,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":145,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":146,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":147,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":148,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":149,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":150,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":151,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":152,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":153,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":154,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":155,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":156,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":157,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":158,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":159,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":160,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":161,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":162,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":163,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":164,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":165,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":166,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":167,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":168,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":169,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":170,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":171,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":172,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":173,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":174,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":175,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":176,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":177,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":178,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":179,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":180,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":181,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":182,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":183,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":184,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":185,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":186,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":187,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":188,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":189,"target_kind":"input","target_name":"input:key","type":"read"},{"offset":190,"target_kind":"input","target_name":"input:key","type
